<?php
define('SITE_ROOT', __DIR__);
require SITE_ROOT . '/vendor/autoload.php';
require_once SITE_ROOT.'/inc/config.php';
require_once SITE_ROOT.'/inc/db.php';
$variables = include SITE_ROOT.'/inc/variables.php';
use Siler\Route;

Route\route(['get', 'post'], '/', 'controllers/index.php');
Route\route(['get', 'post'], '/index.php', 'controllers/index.php');
Route\route(['get', 'post'], '/cat.php', 'controllers/cat.php');
Route\route(['get', 'post'], '/games.php', 'controllers/games.php');
Route\route(['get', 'post'], '/game.php', 'controllers/game.php');
Route\route(['get', 'post'], '/play.php', 'controllers/play.php');
Route\route(['get', 'post'], '/search.php', 'controllers/search.php');
Route\route(['get', 'post'], '/login.php', 'controllers/login.php');
Route\route(['get', 'post'], '/signup.php', 'controllers/signup.php');
Route\route(['get', 'post'], '/logout.php', 'controllers/logout.php');
Route\route(['get', 'post'], '/fogotpass.php', 'controllers/forgotpass.php');
Route\route(['get', 'post'], '/members.php', 'controllers/members.php');
Route\route(['get', 'post'], '/profile.php', 'controllers/profile.php');
Route\route(['get', 'post'], '/account_settings.php', 'controllers/account_settings.php');
Route\route(['get', 'post'], '/page.php', 'controllers/page.php');
Route\route(['get', 'post'], '/credit.php', 'controllers/credit.php');
Route\route(['get', 'post'], '/payout.php', 'controllers/payout.php');
Route\route(['get', 'post'], '/win.php', 'controllers/win.php');
Route\route(['get', 'post'], '/error.php', 'controllers/error.php');
Route\route(['get', 'post'], '/process.php', 'controllers/process.php');
Route\route(['get', 'post'], '/contact.php', 'controllers/contact.php');
Route\route(['get'], '/verify.php', 'controllers/verify.php');
Route\route(['get'], '/payment.php', 'controllers/payment.php');
Route\route(['get'], '/stat.php', 'controllers/stat.php');
Route\route(['get'], '/resolution.php', 'controllers/resolution.php');